-- PÁTIO
CREATE TABLE patio (
                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nome         VARCHAR(120) NOT NULL,
                       endereco     VARCHAR(200),
                       created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- MOTO
CREATE TABLE moto (
                      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      placa        VARCHAR(8)  NOT NULL,      -- ex: ABC1D23
                      modelo       VARCHAR(80) NOT NULL,
                      situacao     VARCHAR(20) NOT NULL,      -- Dentro / Fora
                      patio_id     BIGINT,
                      CONSTRAINT uk_moto_placa UNIQUE (placa),
                      CONSTRAINT fk_moto_patio FOREIGN KEY (patio_id) REFERENCES patio(id)
);

-- FUNCIONÁRIO
CREATE TABLE funcionario (
                             id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome             VARCHAR(120) NOT NULL,
                             cpf              VARCHAR(14)  NOT NULL,
                             telefone         VARCHAR(20),
                             tipo_funcionario VARCHAR(30)  NOT NULL, -- Motoqueiro / Adm. etc
                             moto_id          BIGINT,
                             CONSTRAINT uk_func_cpf UNIQUE (cpf),
                             CONSTRAINT fk_func_moto FOREIGN KEY (moto_id) REFERENCES moto(id)
);

-- USUÁRIO DO SISTEMA (para login)
CREATE TABLE usuario (
                         id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username   VARCHAR(80)  NOT NULL,
                         password   VARCHAR(200) NOT NULL,
                         enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
                         CONSTRAINT uk_usuario_username UNIQUE (username)
);

-- ROLES e relacionamento many-to-many
CREATE TABLE role (
                      id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name  VARCHAR(50) NOT NULL,
                      CONSTRAINT uk_role_name UNIQUE (name)
);

CREATE TABLE usuario_role (
                              usuario_id BIGINT NOT NULL,
                              role_id    BIGINT NOT NULL,
                              PRIMARY KEY (usuario_id, role_id),
                              CONSTRAINT fk_ur_user FOREIGN KEY (usuario_id) REFERENCES usuario(id),
                              CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES role(id)
);
