-- Rastro de movimentação de motos entre pátios
CREATE TABLE movimentacao (
                              id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              moto_id     BIGINT NOT NULL,
                              origem_id   BIGINT NOT NULL,
                              destino_id  BIGINT NOT NULL,
                              data_hora   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              CONSTRAINT fk_mov_moto    FOREIGN KEY (moto_id)   REFERENCES moto(id),
                              CONSTRAINT fk_mov_origem  FOREIGN KEY (origem_id) REFERENCES patio(id),
                              CONSTRAINT fk_mov_destino FOREIGN KEY (destino_id) REFERENCES patio(id)
);

-- Índices úteis
CREATE INDEX idx_mov_moto    ON movimentacao (moto_id, data_hora);
CREATE INDEX idx_mov_origem  ON movimentacao (origem_id, data_hora);
CREATE INDEX idx_mov_destino ON movimentacao (destino_id, data_hora);
